---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/Calibration_Plot_with_error_bars/Calibration_Plot_650nm_corrected.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    folder_url: "/users/18589/articles/304710/master/folder/figures/Calibration_Plot_with_error_bars"
    url: "/users/18589/articles/304710/master/file/figures/Calibration_Plot_with_error_bars/Calibration_Plot_650nm_corrected.png"
